# Generated by Django 4.2.11 on 2026-04-14 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PadraoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carga_horaria', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes', to='conformidade.empresa')),
            ],
            options={
                'verbose_name': 'Padrão de Conformidade',
                'verbose_name_plural': 'Padrões de Conformidade',
                'ordering': ['-ano', 'empresa', 'rubrica'],
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rubrica',
                'verbose_name_plural': 'Rubricas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='VerificacaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('correto', 'Correto'), ('verificar', 'Verificar'), ('incorreto', 'Incorreto')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_verificacao', models.DateTimeField(auto_now_add=True)),
                ('verificado_por', models.CharField(blank=True, max_length=255)),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='conformidade.padraoconformidade')),
            ],
            options={
                'verbose_name': 'Verificação de Conformidade',
                'verbose_name_plural': 'Verificações de Conformidade',
                'ordering': ['-data_verificacao'],
            },
        ),
        migrations.AddField(
            model_name='padraoconformidade',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padroes', to='conformidade.rubrica'),
        ),
        migrations.AlterUniqueTogether(
            name='padraoconformidade',
            unique_together={('rubrica', 'empresa', 'ano')},
        ),
    ]
