# Generated by Django 4.2.11 on 2026-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='arquivo_extrator',
            field=models.FileField(blank=True, null=True, upload_to='verificacoes/extrator/'),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='arquivo_vencimento',
            field=models.FileField(blank=True, null=True, upload_to='verificacoes/vencimento/'),
        ),
    ]
