# Generated by Django 5.0.6 on 2026-04-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0002_verificacaoconformidade_arquivo_extrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacaoconformidade',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='ano_referencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='rubrica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='verificacaoconformidade',
            name='padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='conformidade.padraoconformidade'),
        ),
        migrations.AlterField(
            model_name='verificacaoconformidade',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
