# Generated by Django 5.0.6 on 2026-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0003_remove_verificacaoconformidade_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(default='SEM-CODIGO', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
