# Generated by Django 5.0.6 on 2026-05-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0004_empresa_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='corretos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='incorretos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='resultados_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='total_registros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificacaoconformidade',
            name='verificar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
