# Generated by Django 5.0.6 on 2026-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0005_verificacaoconformidade_corretos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='base_calculo',
            field=models.CharField(blank=True, help_text='Base de cálculo (ex: salário base, horas trabalhadas)', max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='carga_horaria_padrao',
            field=models.IntegerField(blank=True, help_text='Carga horária padrão (horas semanais)', null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='formula_calculo',
            field=models.TextField(blank=True, help_text='Fórmula ou expressão para cálculo da rubrica'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='regras_verificacao',
            field=models.JSONField(blank=True, default=dict, help_text='Regras para validação desta rubrica'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo_calculo',
            field=models.CharField(choices=[('fixo', 'Valor Fixo'), ('percentual', 'Percentual'), ('variavel', 'Variável')], default='fixo', max_length=50),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo_validacao',
            field=models.CharField(choices=[('exato', 'Exato'), ('intervalo', 'Intervalo'), ('tolerancia', 'Com Tolerância')], default='exato', max_length=50),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tolerancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tolerância percentual na verificação', max_digits=5),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='valor_maximo_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='valor_minimo_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
