# Generated by Django on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0006_rubrica_base_calculo_rubrica_carga_horaria_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='base_legal',
            field=models.CharField(blank=True, help_text='Texto explicando a base legal desta rubrica', max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='incidencia',
            field=models.CharField(blank=True, help_text='Incidência sobre encargos e benefícios', max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Características específicas da rubrica'),
        ),
    ]
