# Generated by Django 5.0.6 on 2026-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0007_add_rubrica_detalhes_editaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='tipo_calculo',
            field=models.CharField(blank=True, default='fixo', help_text='Descreva o tipo de cálculo ou fórmula usada', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='tipo_validacao',
            field=models.CharField(blank=True, default='exato', help_text='Descreva o tipo de validação desta rubrica', max_length=255),
        ),
    ]
