# Generated by Django 5.1.6 on 2026-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0008_alter_rubrica_tipo_calculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='criterio_calculo_rubrica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='dc_rubrica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='descricao_rubrica_sigrh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='filtro_valor_fixo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='filtro_vencimento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='legislacao_vigente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='link_para_consulta',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo_de_rubrica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo_orgao_por_rubrica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo_rubrica_analise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='valor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rubrica',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
