# Generated by Django 5.1.6 on 2026-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0009_rubrica_criterio_calculo_rubrica_rubrica_dc_rubrica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
