# Generated by Django 5.0.6 on 2026-10-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformidade', '0010_alter_rubrica_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='link_para_consulta',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
